In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [16]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [32]:
fst = np.reshape(a, (2,6))
sec = np.reshape(a, (6,2))
thd = np.reshape(a, (4,3))
forth = np.reshape(a, (12,1))
fifth = np.reshape(a, (1,12))
print(fst)
print('--------')
print(fifth)


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------
[[12 13 14 15 16 17 18 19 20 21 22 23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [39]:
fst = np.reshape(a, (4,-1))
sec = np.reshape(a, (6,-1))
thd = np.reshape(a, (-1, 3))
forth = np.reshape(a, (-1,4))
fifth = np.reshape(a, (-1,12))
print(thd)
print('-------')
print(sec)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
-------
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Да

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [50]:
a = np.random.random(size = (3,4))
a.flatten()

array([0.3438891 , 0.14089328, 0.68433377, 0.00971492, 0.78786824,
       0.84731011, 0.30984961, 0.47224953, 0.35464889, 0.68533199,
       0.17303207, 0.17171298])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [62]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [63]:
b = np.linspace(20,2,10)
b
# linspace включает крайнюю границу, а arange - нет, + linspace возвращает числа с плавающей точкой

array([20., 18., 16., 14., 12., 10.,  8.,  6.,  4.,  2.])

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [76]:
a =np.zeros((2,2))
b = np.ones((3,2))

v = np.vstack((a, b))
v.size

10

10
a) Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
b) Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
c) Получить матрицу At путем транспонирования матрицы A. 
d) Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
e) Какой размер имеет матрица B? 
f) Получится ли вычислить обратную матрицу для матрицы B и почему?


In [91]:
a = np.arange(1,13)
A = a.reshape((4,3))
At =A.T
B = np.dot(A,At)
size = np.sqrt(B.size)
# Получится, так как определитель B != 0 (d = np.linalg.det(B))

In [92]:
np.random.seed(42)

In [99]:
c = 16 * np.random.random(16)
c

array([ 8.74736447,  2.95767129, 15.51335404, 12.40212517, 15.03198307,
       14.31723761,  9.56639966, 14.74998776,  1.41588003,  3.1357258 ,
        0.72363662,  5.20528529,  6.21883664,  4.34158451, 13.25980015,
        5.70805323])